const data = {
  products: [
    {
      name: 'lorem ipsum text',
      slug: 'lorem-ipsum-text1',
      category: 'Shirts',
      image: 'images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'lorem ipsum text',
      slug: 'lorem-ipsum-text2',
      category: 'Shirts',
      image: 'images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'lorem ipsum text',
      slug: 'lorem-ipsum-text3',
      category: 'Shirts',
      image: 'images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'lorem ipsum text',
      slug: 'lorem-ipsum-text4',
      category: 'Shirts',
      image: 'images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
